# Generated by Django 4.0.6 on 2022-07-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='thingname',
            new_name='thingName',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='thingprice',
            new_name='thingPrice',
        ),
    ]
